### ISSUE TITLE
FontAwesome icons show as squares

### ISSUE THREAD

**Issue by bdw429s** [Computer-Know-how/cblayouts-bootswatch#2]
I had to replace all instance of ../font/ with ../../font/ as it looks like the font files are no longer in the same place.

**Comment by bdw429s** [comment]
Looks like this was fixed in a pull request from Gavin.  The zip file needs to be updated.

**Comment by engens** [comment]
Yes, fixed by Gavin's pull request.  I have updated the .zip file.
